### ISSUE TITLE
Release cadence

### ISSUE THREAD

**Issue by benbrittain** [facebook/buck2#292] opened 2023-06-12 14:06 UTC
As we get closer to rolling out our internal Buck test, we need a way of keeping our repository and our buck2 versions in-sync. 

https://github.com/facebook/buck2/releases provides enough information (the prelude_hash is a particularly helpful touch), but it would be nice if prior prebuilt binaries were available.

Is there any chance we could get tags/releases placed on the repo at a roughly weekly cadence (similar to how https://github.com/facebook/watchman/releases is released)?

This would make our adoption much easier

**Comment by thoughtpolice** [comment] 2023-06-12 14:54
I was going to suggest something like this myself at some point soon, though my suggestion would have been two weeks: once on the first of every month and once on the 15th. It doesn't really matter in the end; some thoughts I had:

- These releases should all probably be thoroughly marked as "pre-releases" to set expectations correctly.
  - I don't know what kind of conditions would need to bet met for a first "stable" release, but I sort of doubt we're close to it at the moment?
- For now, calver (i.e. `v23.06.01` followed by `v23.06.15` in my example) is probably the way to do Buck2 releases, based on the way it's rolled out at Meta, and probably how people will consume it downstream. Maybe calver is just the best way to do things in this project, like watchman?
  - Decoupling the rules from the core binary is actually a huge win for this since it allows you much more leeway in rollouts and end-user control.
- Stable cadence is more important than everything being perfect in every release. Having a release every week or two weeks is fast enough to the point that a user regression can be handled by telling someone to wait a week (or two) for an official fix in a new release as a workaround. Also, many bugfixes can probably be done in the rule code itself, avoiding the need for binary updates.
- It would be nice to document changes/have a CHANGELOG but in lieu of that, "Visit the diff between commit `foobar` and `barbaz`" is probably good enough.
- People should (probably?) be encouraged to update regularly and report issues. You're probably going to have a hard time updating once every 6 months due to the pace of change, but every week or two should be pretty manageable.


But this is something that would be great to see and is mostly a GitHub `.workflow/` file away from happening!

**Comment by benbrittain** [comment] 2023-06-16 19:50
Is this something that a PR would be accepted for?

**Comment by cjhopman** [comment] 2023-06-16 20:46
Yeah, I think a PR for this could be accepted. CalVer of some sort is roughly what we were thinking of and I think twice a month seems fine if that's what people are generally fine with. I'd love to figure out how we can ensure we consistently get an up-to-date CHANGELOG, but I suspect that'll be a challenge (mostly in figuring out how to ensure that it actually gets updates).

**Comment by thoughtpolice** [comment] 2023-06-16 21:44
I think some related changes should also be lined up; for example `buck2 --version` just isn't too useful right now in the open source build (it falls back to a binary hash using blake3 I believe since the elf ID is stripped in some builds) and will need to reflect this.

I'll see if I can cook up a patch series (though I've got a few of those promised, already...)

**Comment by themarwhal** [comment] 2023-07-11 19:13
We will now start tagging twice a month. The first tag is available here: [2023-07-11](https://github.com/facebook/buck2/releases/tag/2023-07-11).

**Closed** 2023-07-11 19:18 UTC

**Comment by benbrittain** [comment] 2023-07-11 19:33
Amazing! Super exciting @themarwhal
